### ISSUE TITLE
ForceAPI v36.0 DescribeSObject returns error Unable to unmarshal response

### ISSUE THREAD

**Issue by jjordan** [nimajalali/go-force#31]
Hi, I believe that v36 of the Salesforce API is returning actual JSON literal true/false values instead of strings for the SObjectField DefaultValue field, which is causing the unmarshalling to fail, which produces this error message:

Unable to unmarshal response to object: force: cannot unmarshal bool into Go value of type string

I couldn't come up with a quick fix, as you'd need to dynamically set the type of DefaultValue based on the value of "Type".  One possibility would be to use a generic interface{} as the type of DefaultValue and then users would have to use reflection + a type assertion to massage it back into the correct type.

**Comment by nimajalali** [comment]
Closing fixed in #30
